# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build: 
      context: ./docker
      dockerfile: Dockerfile

    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: example
    ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
    expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
    # volumes:
    #     - ./docker/my-db-files:/var/lib/mysql
    networks:
      - fullstack
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - fullstack
  mainapp:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
          - db
          - adminer
    restart: always
    expose:
      - 8089
      - 9091
    ports:
      - 8089:8089
      - 9081:9081
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge